services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - consul_data:/consul/data
      - ./consul-config.json:/consul/config/consul-config.json
    command: agent -config-dir=/consul/config
    networks:
      - jenkins

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/file
      - ./../Vault/vault-config:/vault/config
    networks:
      - jenkins
    depends_on:
      - consul
    command: vault server -config=/vault/config/vault.hcl

volumes:
  consul_data:
  vault_data:

networks:
  jenkins:
    external: true
