services:
  app:
    image: jenkins/jenkins:2.506
    container_name: jenkins
    user: root
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /home/oleg/.ssh:/var/jenkins_home/.ssh
    networks:
      - jenkins

  #agent:
   # image: jenkins/inbound-agent
   # container_name: jenkins-agent
   # environment:
   #   - JENKINS_URL=http://127.0.0.1:8080
   #   - JENKINS_AGENT_WORKDIR=/var/jenkins_home/agent
   #   - JENKINS_SECRET=REPLACE_WITH_AGENT_SECRET
   #   - JENKINS_NAME=agent-1
   # depends_on:
   #   - jenkins
   # networks:
   #   - jenkins-net

  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - jenkins

volumes:
  jenkins_home:

networks:
  jenkins:
    external: true
