services:
  app:
    image: jenkins/jenkins
    container_name: jenkins
#    user: root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /home/oleg/.ssh:/var/jenkins_home/.ssh
      - ~/Downloads:/tmp/
#      - /home/oleg/.ssh:/root/.ssh
    networks:
      - jenkins

  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - jenkins

volumes:
  jenkins_home:

networks:
  jenkins:
    external: true

