services:

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.23.41
    container_name: artifactory
    ports:
      - "8081:8081"
    environment:
      - JF_SHARED_NODE=true
      - ARTIFACTORY_OPENTRACING_ENABLED=false
      - ARTIFACTORY_OPENTRACING_DISABLED=true
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    networks:
      - jenkins

volumes:
  artifactory_data:

networks:
  jenkins:
    external: true
